-- MySQL Script generated by MySQL Workbench
-- Tue Jan 24 08:18:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hangar_eccomerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hangar_eccomerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hangar_eccomerce` DEFAULT CHARACTER SET utf8mb4 ;
USE `hangar_eccomerce` ;

-- -----------------------------------------------------
-- Table `hangar_eccomerce`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hangar_eccomerce`.`Roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hangar_eccomerce`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hangar_eccomerce`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(45) NULL,
  `fnac` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Roles_id` INT ,
  PRIMARY KEY (`id`, `Roles_id`),
  INDEX `fk_Usuarios_Roles_idx` (`Roles_id` ASC),
  CONSTRAINT `fk_Usuarios_Roles`
    FOREIGN KEY (`Roles_id`)
    REFERENCES `hangar_eccomerce`.`Roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hangar_eccomerce`.`Producto_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hangar_eccomerce`.`Producto_categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hangar_eccomerce`.`Producto_colores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hangar_eccomerce`.`Producto_colores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hangar_eccomerce`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hangar_eccomerce`.`Productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `descuento` VARCHAR(45) NULL,
  `Producto_categorias_id` INT NULL,
  `Producto_colores_id` INT NULL,
  `Producto_categorias_id1` INT NOT NULL,
  `Producto_colores_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `Producto_categorias_id1`, `Producto_colores_id1`),
  INDEX `fk_Productos_Producto_categorias1_idx` (`Producto_categorias_id1` ASC),
  INDEX `fk_Productos_Producto_colores1_idx` (`Producto_colores_id1` ASC),
  CONSTRAINT `fk_Productos_Producto_categorias1`
    FOREIGN KEY (`Producto_categorias_id1`)
    REFERENCES `hangar_eccomerce`.`Producto_categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Producto_colores1`
    FOREIGN KEY (`Producto_colores_id1`)
    REFERENCES `hangar_eccomerce`.`Producto_colores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
